name: Deploy Frontend

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "14"

      - name: Install dependencies
        run: npm install

      - name: Build the project
        run: npm run build

      - name: Deploy to S3
        uses: jakejarvis/s3-sync-action@master
        with:
          args: --acl public-read --follow-symlinks --delete
        env:
          AWS_S3_BUCKET: ${{ secrets.imagebuddy }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AKIAU6GDY52SCEGD2MNB }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.NPIKRMxOoh4g3F/I2rDzhvr5aC03yG7L418LIP1f }}
          AWS_REGION: ${{ secrets.Europe (Stockholm) eu-north-1 }}

      - name: Run Cypress tests
        run: npm run cypress:run
